# Generated by Django 3.0.6 on 2020-05-19 20:25

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtailmd.utils.MarkdownField(),
        ),
    ]
